### ISSUE TITLE
weather widget ->  TypeError: mapped is undefined

### ISSUE THREAD

**Issue by knowthelist** [nesges/Widgets-for-fhem-tablet-ui#1]
ich versuche aber gerade das weather widget bei mir einzubinden.  PROPLANTA liefert bei mir "Schneeregen", damit klappt das mapping nicht: TypeError: mapped is undefined
Wie soll diese Schleife bewirken?
[quote]                    var mapped = _weather.translationmap[val];
                    while(typeof mapped != "undefined" && !mapped.match(/^:/)) {
                        mapped = _weather.translationmap[mapped];
                    }[/quote]

Danach muss sicherheitshalber nochmal auf (typeof mapped != "undefined") geprüft werden bevor versucht wird, mapped zu benutzen.

**Comment by nesges** [comment]
Genau, da waren wir gleichzeitig dran, hab's grade gefixt. Danke für die Meldung!

Schleife, damit man translationmap als Baum aufbauen kann. Vor der Trennung in translationmap und meteoconsmap/kleinklimamap war alles in einem Array; da war das notwendig. Jetzt eigentlich nicht mehr, aber ich halt mir die Option mal offen.
